version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Install dependencies"
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - echo "Packaging Lambda function"
      - cp -r . package/
      - cd package && zip -r ../lambda_package.zip .
artifacts:
  files:
    - lambda_package.zip
