steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fastapi-app']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - gcloud
    - run
    - deploy
    - fastapi-service       # 部署後的 Cloud Run 服務名稱，可自行更改
    - --image=gcr.io/$PROJECT_ID/fastapi-app
    - --region=us-central1  # 根據你需求選擇區域
    - --platform=managed
    - --allow-unauthenticated
