steps:
  # 建構 Docker 映像檔
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$IMAGE', '.']

  # 推送映像檔到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$IMAGE']

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud', 'run', 'deploy', 'fastapi-service',
        '--image', '$IMAGE',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - '$IMAGE'

options:
  logging: CLOUD_LOGGING_ONLY
